fix: add 'arcade' to poetry.lock file
cat-dev-group/pyweek-32 pull request #1
Opened 2021-09-19 18:28 UTC by brad90four

2021-09-19 19:23 UTC, brad90four commented on tox.ini
> +max-line-length = 100
```suggestion
max-line-length = 121
```
I like longer lines, but 100 is fine too.

2021-09-19 19:25 UTC, dawnofmidnight commented on tox.ini
> +max-line-length = 100
Maybe something like 119, so it's exactly 40 chars above.

2021-09-19 21:35 UTC, doublevcodes requested changes
Hey, good effort:
1. I'm not sure how much I like the whole ignore everything and negate what we need in .dockerignore
2. Just use the Python .gitignore template provided by GitHub and add in .vscode and .idea
3. Possibly add in pre-commit

Also have a look at the changes I've suggested.

2021-09-19 21:35 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +        uses: actions/setup-python@v2.2.2
```suggestion
        uses: actions/setup-python@v2.2
```
I wouldn't pin to a patch.

2021-09-19 21:35 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +    name: flake8
This is unnecessary if the job name is also flake8.

2021-09-19 21:35 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +  flake8:
```suggestion
  flake8:
    env:
      PIP_USER: 1  # Install as a user
      POETRY_VIRTUALENVS_CREATE: false  # Prevent package manager from creating venv
```

2021-09-19 21:35 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +        run: poetry run black . --check --diff
Black has its own official docker image, I would check that out.

2021-09-19 21:35 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +        run: poetry run isort . --check --diff
Isort also has its own docker image.

2021-09-19 21:35 UTC, doublevcodes commented on Dockerfile
> +FROM --platform=linux/amd64 python:3.9-slim
Why is this for AMD64?

2021-09-19 21:35 UTC, doublevcodes commented on tox.ini
> +max-line-length = 100
111?

2021-09-19 21:36 UTC, dawnofmidnight commented on .github/workflows/lint-test.yml
> +  flake8:
Would it work to set this as an env for the whole file?

2021-09-19 21:37 UTC, dawnofmidnight commented on .github/workflows/lint-test.yml
> +        run: poetry run black . --check --diff
Why isn't the CLI fine?

2021-09-19 21:37 UTC, dawnofmidnight commented on Dockerfile
> +FROM --platform=linux/amd64 python:3.9-slim
This makes sure it runs on the Linux kernel rather than having issues with an M1.

2021-09-19 21:39 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +  flake8:
Yes, that is also an option if we don't use the black and isort docker images

2021-09-19 21:39 UTC, dawnofmidnight commented
> 1. I'm not sure how much I like the whole ignore everything and negate what we need in .dockerignore

Why not? Docker doesn't need most of the files we have, so I think it's fine to just ignore most of it.

> 2. Just use the Python .gitignore template provided by GitHub and add in .vscode and .idea

Err, where can I find that template?

> 3. Possibly add in pre-commit

That sounds good, I can do that.

2021-09-19 21:39 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +        run: poetry run black . --check --diff
Because it's more steps and takes longer. Plus GitHub caches the image for us.

2021-09-19 21:40 UTC, doublevcodes commented on Dockerfile
> +FROM --platform=linux/amd64 python:3.9-slim
Ah ok.

2021-09-19 21:40 UTC, dawnofmidnight commented on .github/workflows/lint-test.yml
> +        uses: actions/setup-python@v2.2.2
I can just pin to a major version as there shouldn't be any breaking changes.

2021-09-19 21:40 UTC, dawnofmidnight commented on .github/workflows/lint-test.yml
> +        run: poetry run black . --check --diff
Ok. Is there a good "setup docker" action you know of?

2021-09-19 21:42 UTC, dawnofmidnight commented on .github/workflows/lint-test.yml
> +        run: poetry run black . --check --diff
Or, I could set it up in pre-commit with the url rather than having it as a dependency. Either works.

2021-09-19 21:42 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +        uses: actions/setup-python@v2.2.2
Sounds good.

2021-09-19 21:44 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +        run: poetry run black . --check --diff
Sorry I'm being an idiot. There's no docker involved. But check out something like: https://black.readthedocs.io/en/stable/integrations/github_actions.html#usage

2021-09-19 21:44 UTC, doublevcodes commented on .github/workflows/lint-test.yml
> +        run: poetry run isort . --check --diff
Look here: https://pycqa.github.io/isort/docs/configuration/github_action.html

2021-09-24 21:32 UTC, dawnofmidnight commented
#3 Takes care of this.

2021-09-24 21:32 UTC, closed without merging