feat: add game window and basic controls
cat-dev-group/pyweek-32 pull request #3
Opened 2021-09-22 19:34 UTC by brad90four

Main window and basic game controls

2021-09-24 21:38 UTC, dawnofmidnight submitted a review, later dismissed
I can't test the code right now, but I've done a quick review. Also, can we make sure to fill in all the placeholders before this is merged?

2021-09-24 21:38 UTC, dawnofmidnight commented on src/SCREAMING_SNAKE_SHOOTER.py
> +SCREEN_HEIGHT = 1000
Can we set up some sort of config system with env vars (with sensible defaults)?

2021-09-24 21:38 UTC, dawnofmidnight commented on src/base_classes/FlyingEnemy.py
> +        # I like to move it move it
This is unnecessary

2021-09-24 21:38 UTC, dawnofmidnight commented on src/error_throwing.py
> +"""error_throwing.py is used for generating the errors the game loop uses for the errors the user has to shoot."""
Is this line necessary? And if so, can we add a gap between this line and the imports?

2021-09-24 21:38 UTC, dawnofmidnight commented on src/views/StartView.py
> +        # Don't start if print screen or windows key
Is it intended that this is not part of the doc comment?

2021-09-24 21:38 UTC, dawnofmidnight commented on src/SCREAMING_SNAKE_SHOOTER.py
> +        # Commenting out for now, should the player be able to move up or down?
Can we decide on this?

2021-09-24 21:38 UTC, dawnofmidnight commented on src/SCREAMING_SNAKE_SHOOTER.py
> +        # Commenting out for now, should the player be able to move up or down?
Same as above

2021-09-24 21:38 UTC, dawnofmidnight commented on src/SCREAMING_SNAKE_SHOOTER.py
> +        # commenting out the top and bottom for now
Same as above

2021-09-24 22:52 UTC, brad90four commented on src/views/StartView.py
> +        # Don't start if print screen or windows key
I meant for it to be temporary during testing, since I can start a screen recording with `Win` + `G` to share the status.

2021-09-24 23:07 UTC, brad90four commented on src/SCREAMING_SNAKE_SHOOTER.py
> +SCREEN_HEIGHT = 1000
Done! New `.env` has all of these

2021-09-25 07:43 UTC, Arnav-2004 commented on src/SCREAMING_SNAKE_SHOOTER.py
> +SCREEN_HEIGHT = 1000
`.env` doesn't really make sense for this, can we just have a constants file instead

2021-09-25 08:00 UTC, Arnav-2004 requested changes

2021-09-25 08:07 UTC, Arnav-2004 requested changes

2021-09-25 08:07 UTC, Arnav-2004 commented on src/SCREAMING_SNAKE_SHOOTER.py
> +        # ):
Same as above if we are keeping this.

2021-09-25 11:18 UTC, dawnofmidnight commented on src/views/StartView.py
> +        # Don't start if print screen or windows key
Ok. Could you add a ! after the # so that some editors will highlight it?

2021-09-25 11:19 UTC, dawnofmidnight commented on src/SCREAMING_SNAKE_SHOOTER.py
> +SCREEN_HEIGHT = 1000
It's just a couple values that aren't always needed, so I don't think we need to use a separate constants file.

2021-09-25 11:21 UTC, dawnofmidnight commented on .env
> +SCREEN_WIDTH = 1000
I don't think we should at a `.env`, but instead, make sensible defaults in the Python code, maybe with a try-catch.

2021-09-25 22:58 UTC, VirdanTheBurden approved these changes

2021-09-25 22:58 UTC, Shom770 commented on src/SCREAMING_SNAKE_SHOOTER.py
> +        ):
Black was the one who fixed this

2021-09-25 22:58 UTC, Shom770 approved these changes

2021-09-25 23:16 UTC, merged